name: flutter_pokedex
description: "Code challenge para Flutter Developers."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.1.3
  shared_preferences: ^2.0.5
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  intl: ^0.19.0
  provider: ^6.1.2

  #DATA/DOMAIN
  pokemon:
    path: packages/core/pokemon
  pokedex:
    path: packages/core/pokedex

  #CORE
  network:
    path: packages/common/network
  failure:
    path: packages/common/failure
  state_manager:
    path: packages/common/state_manager
  storage:
    path: packages/common/storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  lints: ^3.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.8
  bloc_test: ^9.1.6

flutter:
  uses-material-design: true
