name: network
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.1.3
  http: ^1.0.0

  failure:
    path: ../failure

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  lints: ^3.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.8



flutter:
